FROM mcr.microsoft.com/dotnet/aspnet:9.0 as base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["GatewayService.csproj","./"]
RUN dotnet restore "./GatewayService.csproj"

COPY . .
RUN dotnet publish "GatewayService.csproj" -c Release -o /app/publish

FROM base as final
WORKDIR /app

COPY --from=build /app/publish .

#ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "GatewayService.dll"]