FROM mcr.microsoft.com/dotnet/aspnet:9.0 as base
RUN apt-get update && apt-get install -y curl
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["GatewayService.csproj","./"]
RUN dotnet restore "GatewayService.csproj"

COPY . .
WORKDIR "/src/."
RUN dotnet build "GatewayService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GatewayService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

#ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "GatewayService.dll"]